import{a as b,S as f,i as L}from"./assets/vendor-da186403.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const w="https://pixabay.com/api/";async function S(t,r,a=15){const s="42541165-a3d46185342d32ff55345145c";try{return(await b.get(`${w}?key=${s}&q=${encodeURIComponent(t)}&page=${r}&per_page=${a}`)).data.hits}catch{throw new Error("Failed to fetch images from Pixabay API")}}const $="/goit-js-hw-12/assets/bi_x-octagon-80ee8afe.svg";function q(t){const r=document.querySelector(".gallery"),a=t.map(({webformatURL:s,largeImageURL:e,tags:o,likes:l,views:p,comments:h,downloads:v})=>`<li class="gallery-item"> 
		<div class="gallery-card">
		<a class="gallery-link" "href="${e}">
            <img class="gallery-image" src="${s}" alt="${o}" />
						</a>
            <div class="image-details">
                <p class="detail-value"><b>Likes:</b> ${l}</p>
                <p class="detail-value"><b>Views:</b> ${p}</p>
                <p class="detail-value"><b>Comments:</b> ${h}</p>
                <p class="detail-value"><b>Downloads:</b> ${v}</p>
            </div>
						</div>
        </li>`).join("");r.insertAdjacentHTML("beforeend",a),new f(".gallery a",{captionsData:"alt",captionDelay:250})}function i(t){L.error({title:"Error",message:t,position:"topCenter",class:"popup-message",theme:"dark",backgroundColor:"#ef4040",messageColor:"#fff",position:"topRight",timeout:3e3,iconUrl:$})}const c=document.querySelector(".form-submit");c.addEventListener("mouseover",function(){c.classList.add("hover-effect")});c.addEventListener("mouseout",function(){c.classList.remove("hover-effect")});let u="",d=1,n,m;document.addEventListener("DOMContentLoaded",()=>{const t=document.querySelector(".form"),r=document.querySelector(".form-input"),a=document.querySelector(".gallery");n=document.querySelector(".loadmore"),m=document.querySelector(".loading-more"),new f(".gallery a",{captionsData:"alt",captionDelay:250}),t.addEventListener("submit",async s=>{s.preventDefault(),a.innerHTML=null,u=r.value.trim();const e=document.querySelector(".loader");if(e.classList.add("loading"),u===""){i("Please enter a search term.");return}d=1,await g(),e.classList.remove("loading")}),n.addEventListener("click",async function(){d++,n.style.display="none",m.style.display="block";const s=y();s&&window.scrollBy({top:s*2,behavior:"smooth"}),await g()}),y()});function y(){const t=document.querySelector(".gallery-item");if(t){const r=t.getBoundingClientRect().height*2;return console.log(r),r}return null}async function g(){try{const t=await S(u,d),r=t.totalHits,a=d*15;if(t.length===0){i("Sorry, there are no images matching your search query. Please try again!");return}if(a>=r){n.style.display="none",i("We're sorry, but you've reached the end of search results."),console.log(t.length);return}q(t),t.length<15?(n.style.display="none",i("We're sorry, but you've reached the end of search results.")):n.style.display="block"}catch{i("An error occurred while fetching data. Please try again later.")}finally{m.style.display="none"}}
//# sourceMappingURL=commonHelpers.js.map
